### ISSUE TITLE
 add tooltip language filter

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#110]
add language to comment-form-handling to support when in replies-only mode: "Receive replies to your comment via email"

**Comment by cyberhobo** [comment]
The language belongs to commentium, so what we need here is a filter. And since we want this in premium too, we'll have to add the filter to both replyable and legacy-posts. You're wanting the Replyable release to be 2.2.0?

**Comment by Vernal** [comment]
Yes sir indeederoonie.
