### ISSUE TITLE
update Helpscout chat beacon

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#123]
The .js for the beacon has changed and should be modified to this:
`<script type="text/javascript">!function(e,t,n){function a(){var e=t.getElementsByTagName("script")[0],n=t.createElement("script");n.type="text/javascript",n.async=!0,n.src="https://beacon-v2.helpscout.net",e.parentNode.insertBefore(n,e)}if(e.Beacon=n=function(t,n,a){e.Beacon.readyQueue.push({method:t,options:n,data:a})},n.readyQueue=[],"complete"===t.readyState)return a();e.attachEvent?e.attachEvent("onload",a):e.addEventListener("load",a,!1)}(window,document,window.Beacon||function(){});</script>
<script type="text/javascript">window.Beacon('init', 'e4247595-68e9-4d11-b901-c438a539e627')</script>`

**Comment by ronalfy** [comment]
New code added.

<img width="379" alt="Screen Shot 2019-07-03 at 4 11 42 PM" src="https://user-images.githubusercontent.com/636521/60625388-45f38100-9dad-11e9-8e36-f73cb7096f8e.png">
