### ISSUE TITLE
Sort user subscriptions chronologically

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#124]
In profile.php we list out the conversations a user is subscribed to. Can we look into sorting this chronologically based on when they subscribed?
![conversation-subscriptions](https://user-images.githubusercontent.com/80932/60620766-1131fa80-9daa-11e9-9e33-27ab76097ebe.jpg)

**Comment by ronalfy** [comment]
We can sort by meta ID in ascending order, which should show the subscriptions based on when they subscribed.
