### ISSUE TITLE
Add base urls to avatars in the email templates

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#125]
Avatar plugins such as WP User Avatar will be missing the base url to the user avatar in Replyable emails. Let's add the base url to all user avatars. This seems to do the trick (submitted by a user to Helpscout:

`/**
* Ensure avatars use absolute url to image.
*
* When Replyable sends emails with user avatars added via
* WP User Avatar, the avatar images have relative urls and hence
* show a broken image when viewing the emails.
*/
add_filter( 'get_avatar', function ( $avatar, $id_or_email, $size, $default, $alt ) {
return preg_replace( '|( src=[\'"])(/[^/]+)|', '${1}' . get_site_url() . '${2}', $avatar );
}, 10, 5 );`

**Comment by ronalfy** [comment]
Hmm, that's a dangerous regex. I'll need some time to ponder this. Let's talk about this during tomorrow's meeting.
