### ISSUE TITLE
Add a notice to existing users to switch to Labs

### ISSUE THREAD

**Issue by cyberhobo** [postmatic/postmatic-basic#21]

**Comment by cyberhobo** [comment]
@Vernal, I've added the notice, now you can revamp content in labs-notice.php and download-modal.php.

**Comment by Vernal** [comment]
Hey @cyberhobo I've got this wrapped up but removed the dismiss button. My prefered behaviour would be that the _tell me what to do_ button acts to dismiss the notice as well. Can you do that?
