### ISSUE TITLE
Make reply-to address commenting@gopostmatic.com

### ISSUE THREAD

**Issue by cyberhobo** [postmatic/postmatic-basic#31]

**Comment by Vernal** [comment]
I'm guessing this is for non-api replies, right? If so, where does that box go and what do we do with it? Should we do a donotreply@ instead?

**Comment by cyberhobo** [comment]
Correct. I thought you wanted to set up a canned responder using zapier or
something. Currently that address will be routed by No-IP I think.

**Comment by Vernal** [comment]
Ahhhh you are correct. Proceed young soldier, but let’s use donotreply@gopostmatic.com.


On November 16, 2016 at 11:01:04 AM, Dylan Kuhn (notifications@github.com) wrote:

Correct. I thought you wanted to set up a canned responder using zapier or
something. Currently that address will be routed by No-IP I think.

**Comment by cyberhobo** [comment]
That's ready to go.

**Comment by cyberhobo** [comment]
I think that last commit fixes the "Array to String conversion" error you saw when comment-subscribing.
