### ISSUE TITLE
Add in module checkbox for monetization

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#4]
Resurrect the old BSA checkbox. Trigger a modal upon activation giving the user the ability to shoot an email to support to learn about monetization opportunities.

**Comment by cyberhobo** [comment]
So we are not resurrecting any of the actual BSA functionality, just a modal with a button to send an email? Can we just use a button rather than a checkbox?

**Comment by Vernal** [comment]
Actually, if you’re up to it let’s do a checkbox with a tab. We can use it to fill users in on what is available for monetization and give them a button to request we contact them…


On May 20, 2016 at 3:07:04 PM, Dylan Kuhn (notifications@github.com) wrote:

So we are not resurrecting any of the actual BSA functionality, just a modal with a button to send an email? Can we just use a button rather than a checkbox?

**Comment by cyberhobo** [comment]
Branch monetization-tab is ready for content in `templates/monetization-tab.php`.
