### ISSUE TITLE
Use comment reply template when mailing locally

### ISSUE THREAD

**Issue by cyberhobo** [postmatic/postmatic-basic#43]
You wanted to do this right @vernal? We forgot it earlier.

**Comment by Vernal** [comment]
Can you elaborate?

**Comment by cyberhobo** [comment]
Current postmatic basic does not use the fancier comment reply template when mailing via wp_mail. Should we start? We'd have to remove the email reply links and prompts of course.

**Comment by Vernal** [comment]
Yes sir. Fancy we go.


On November 2, 2016 at 10:51:31 AM, Dylan Kuhn (notifications@github.com) wrote:

Current postmatic basic does not use the fancier comment reply template when mailing via wp_mail. Should we start? We'd have to remove the email reply links and prompts of course.
