### ISSUE TITLE
Remove download prompt from upgrade message

### ISSUE THREAD

**Issue by cyberhobo** [postmatic/postmatic-basic#56]
Implementation notes:
![screen shot 2016-11-22 at 8 24 08 am](https://cloud.githubusercontent.com/assets/286838/20532400/b455a0b0-b08e-11e6-9993-b301928b37a6.png)

**Comment by cyberhobo** [comment]
I think all we need to do is set the is_premium Freemius init flag. @Vernal if you want to try this on c9, make that flag true in your wp-config.

**Comment by Vernal** [comment]
It's not that simple. By defining is_premium the user is never asked to opt-in (and thus does not go through the upgrade sales process). 

If you are proposing we flip is_premium at the point of purchase... then yes, that would work. We would have to flip it back if/when they downgrade or the trial ends... thoughts?

**Comment by cyberhobo** [comment]
Alright, I will try the implementation Vova suggests.

**Comment by cyberhobo** [comment]
We'll have to wait for a freemius SDK update for the sticky message filter to work, but after that's verified this should be done.

**Comment by Vernal** [comment]
Go for it.
