### ISSUE TITLE
Remove upgrade notice and tab when on paid plan

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#57]

**Comment by cyberhobo** [comment]
There will be a phase, normally very short, when a user has upgraded in Freemius but service is not yet enabled on MS. Should we add some kind of message explaining this state?

**Comment by Vernal** [comment]
How long are we looking at?

**Comment by cyberhobo** [comment]
The time it takes for the freemius webhook to fire, get caught by MS, MS send a key to the site, and the site use that key to pull its new configuration from MS. Add retry time if any of those steps fail.

**Comment by Vernal** [comment]
I’d say let’s not worry about it until it becomes a problem.


On November 28, 2016 at 4:56:32 PM, Dylan Kuhn (notifications@github.com)
wrote:

The time it takes for the freemius webhook to fire, get caught by MS, MS
send a key to the site, and the site use that key to pull its new
configuration from MS. Add retry time if any of those steps fail.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/postmatic/postmatic-basic/issues/57#issuecomment-263407064>,
or mute the thread
