### ISSUE TITLE
Customize wording on upgrade prompt

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#65]
<img width="1056" alt="screen shot 2016-12-07 at 1 19 43 pm" src="https://cloud.githubusercontent.com/assets/80932/20980756/d6c09478-bc7f-11e6-8f68-c9a2b358851c.png">

**Comment by cyberhobo** [comment]
I think you won't see this message after is_premium gets flipped to true. But I'm still not sure we're doing this on all the hooks we need to, or that the hooks fire before the message is shown. 

Now that you're not forcing is_premium to false, see if the behavior changes.
