### ISSUE TITLE
The upgrade notice isn't noticing an upgrade

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#66]
Even though i'm on daily discourse i still get the upgrade notice on the welcome screen...
<img width="1038" alt="screen shot 2016-12-07 at 2 05 03 pm" src="https://cloud.githubusercontent.com/assets/80932/20982370/39194eac-bc86-11e6-9e19-4a90e15e1389.png">

**Comment by cyberhobo** [comment]
I think maybe your webhooks weren't set up yet @Vernal. Can you try it now that they're hooked up?
