### ISSUE TITLE
Remove welcome to Postmatic welcome notice

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#67]
<img width="1115" alt="screen shot 2016-12-08 at 10 33 06 pm" src="https://cloud.githubusercontent.com/assets/80932/21036766/5e05a9d4-bd96-11e6-802d-4cb38aae0ebc.png">

**Comment by cyberhobo** [comment]
I wonder if the bug label would be more useful if it's limited to things that have been released? As it is this will look like 2.1 fixed a bug in 2.0.x, which isn't really the case.

**Comment by Vernal** [comment]
I made a new label! Tweak!

**Comment by cyberhobo** [comment]
:+1:
