### ISSUE TITLE
Make welcome tab messaging conditional based on:

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#68]
If never been on trial
do this
else if on trial
do this
else if been on trial but didn’t convert
do this
else if freemius thinks they have a paying plan but there is no key
do this
else (they are paying and set)
do this

Here are the relevant freemius methods:
1. is_trial_utilized() - if trial was ever activated
2. is_trial() - if currently runs in a trial (will return false if trial over)
3. has_active_valid_license() - checks if has an active & valid license license
4. can_use_premium_code() - checks if in trial or has a valid license

**Comment by cyberhobo** [comment]
They need a key if they're on trial too, no?

Also keep in mind if they're coming from Postmatic they may have a key, but never been on trial.

**Comment by Vernal** [comment]
They do need a key on trial, yes.

As far as the legacy users, that could be triggered with is_trial_utilized. 

Does that give you what you need... or do you want something more specific?

**Comment by cyberhobo** [comment]
Just wanted to make sure the logic you specified is really what you want. As you have it you'll get the trial message whether you have a key or not.

**Comment by cyberhobo** [comment]
Also, would you prefer a separate template for each case, or do you want to put the conditions inside the `core-options-promo.php` template?

**Comment by Vernal** [comment]
I’m fine putting them inside the existing….

**Comment by cyberhobo** [comment]
From Slack: we could make two additional promo messages. Both only if they have no paid Freemius plan but do have an API key. One for API transport, the other for local.

**Comment by cyberhobo** [comment]
Alright @Vernal that gives you two more areas to fill in. Most of the strings in the template are not internationalized, let me know when you're ready and I can do that too.

**Comment by cyberhobo** [comment]
@Vernal on branch 2.1.0-beta2-dev there is a pending activation section ready to fill in.

**Comment by Vernal** [comment]
ok back in your court

**Comment by cyberhobo** [comment]
Language is internationalized, that should wrap it up.
