### ISSUE TITLE
Display the Knowledge Base link in the freemius menu on all plans

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#79]

**Comment by cyberhobo** [comment]
Do you mean you want to turn on the wp.org support forum link @Vernal ?

**Comment by Vernal** [comment]
Not to the forum, no. The knowledgebase, which I have configured to point to help scout.

**Comment by cyberhobo** [comment]
I don't see that in the SDK Integration settings. Where should I look?

**Comment by Vernal** [comment]
I’m not sure. In Freemius it is a setting for Knowledge Base link. See attached.

**Comment by cyberhobo** [comment]
Vova says it is currently not used anywhere, but will be in the future.
