### ISSUE TITLE
Fatal error: Cannot redeclare scb_init()

### ISSUE THREAD

**Issue by cyberhobo** [postmatic/postmatic-basic#80]
Observed when running with wp-pagenavi:

```
Plugin could not be activated because it triggered a fatal error.

Fatal error: Cannot redeclare scb_init() (previously declared in /nas/content/live/hopmeldev/wp-content/plugins/wp-pagenavi/scb/load.php:101) in /nas/content/live/hopmeldev/wp-content/plugins/postmatic/vendor/scribu/scb-framework/load-composer.php on line 12
```

**Comment by cyberhobo** [comment]
@Vernal in the case of wp-pagenavi, it appears that activating Replyable before PageNavi is a workaround in that particular case.

**Comment by Vernal** [comment]
Thanks boss.

**Comment by misfist** [comment]
I'm experiencing the same issue using a plugin that makes use of the posts-to-posts plugin.

**Comment by cyberhobo** [comment]
@misfit did you try deactivating both plugins, then activating replyable before posts-to-posts?

**Comment by cyberhobo** [comment]
@misfist As an experimented I forked wp-scb-framework and tried having Composer use the standard loader. Give the following build a try if you like:
[postmatic-2.1.3.zip](https://github.com/postmatic/postmatic-basic/files/740512/postmatic-2.1.3.zip)

**Comment by misfist** [comment]
@cyberhobo - Thanks for this! I'll check it out and report back.

**Comment by danaskallman** [comment]
@cyberhobo that zip file shared works, the fatal error prevent activation. Thanks!

**Comment by cyberhobo** [comment]
Thanks @danaskallman - I actually forgot to close this issue, the "loading voodoo" should be included in the current releases also, please let me know if they do not.

**Comment by danaskallman** [comment]
@cyberhobo I just tried version 2.2.1 and I am getting the fatal error. posts-to-posts in installed as it's own plugin in the instance I would use this alongside it.

**Comment by cyberhobo** [comment]
Thanks for letting me know - I'll reopen this and target our next release. Meanwhile it should be okay to use the zip that works.

**Comment by danaskallman** [comment]
Sounds good, I'll follow updates. Thanks!

**Comment by Jon007** [comment]
just to add, other plugins such as BadgeOS also affected by this issue.
Also note the large number of \vendor directories included contributes to making this one of the largest wordpress plugins ..
