### ISSUE TITLE
Remove all freemius submenu items

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#85]
This is redundant - the user can get to it from the Account tab as well as the Upgrade tab.

**Comment by Vernal** [comment]
Modified the todos. Remove all freemius submenu items. I'm going to find other ways to get there.

**Comment by cyberhobo** [comment]
Done in 88598b3. 

There are API methods to generate each of those URLs - I can convert static URLs for you when you're ready.

**Comment by Vernal** [comment]
Sweet.
