### ISSUE TITLE
Email footer text is not working on paid plans

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#88]
Defining the email footer text does nothing on paid plans. It should replace _Sent from XXX. Delivered by Replyable - Two-way email commenting for WordPress._

**Comment by cyberhobo** [comment]
I committed a partial fix that will include footer text, however it goes in the `{{{footer_html}}}` area, while the `{{{credit_html}}}` contains the Sent/Delivered message. In Postmatic we offered premium users a checkbox to disable the Delivered part of that. Should we bring back that checkbox, or change how the whole thing works to what you described?

**Comment by Vernal** [comment]
Oh cool. Let’s just bring back that checkbox.
