### ISSUE TITLE
Look into unregistering scb on uninstall

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#9]
Like here:
https://vernal.slack.com/archives/postmatic/p1464283533000018

**Comment by cyberhobo** [comment]
I don't think the uninstall hook was being registered in a way the would conflict with freemius (or even fire), but this should remove it: https://github.com/postmatic/postmatic-basic/commit/73f8b6e6052a31499ad6c363a94f23a4acc649f3
