### ISSUE TITLE
Comment checkbox tooltip disables submit on touch screens

### ISSUE THREAD

**Issue by cyberhobo** [postmatic/postmatic-basic#91]
Report from nitaimeditation.com:

>The popup to the right of the above line saying "Get only replies to your comment, the best of the rest,…" is highly annoying in mobile browsers and even in desktops and some commenters both from the iPhone and Android have reported that they can't tap the Submit comment button. I think the problem is that it pops up when mousing or tapping that whole life which is annoying. It should pop up only which tapping or mousing over the question mark icon on the right of this line not the whole line please.

**Comment by Vernal** [comment]
Alright. Looking.

**Comment by Vernal** [comment]
Do you know what the active theme or url was?

**Comment by cyberhobo** [comment]
The same as the current theme, Promobile.

**Comment by Vernal** [comment]
Ok, fixed with 1053ad3626c4c10377cef71ec605f24a0c25927b
