### ISSUE TITLE
Author comment notifications broken when on free plan

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#94]
This is an interesting catch just pointed out to me by a user.

If you are using Replyable in free mode the stock WordPress comment notifications do not send as they should.

The default behaviour is that WP sends a new comment notice to the post author according to the setting on settings>discussion. 

1. When Replyable is enabled but in free mode the post author does not get a wp comment notification (not ok)
2. When Replyable is enabled and on the tier1 plan the author does get the wp notification (correct), but not the replyable notification (correct).
3. When on tier2 and above the wp notification is suppressed (correct) and the author gets the Replyable notification (correct).

So it seems that when #1 is true the post author should still get the stock wp comment notification email.

**Comment by cyberhobo** [comment]
I'm not able to reproduce 1, the native comment notification goes out on my install. These are the discussion settings I tried :
<img width="663" alt="screenshot 2017-02-15 20 09 08" src="https://cloud.githubusercontent.com/assets/286838/23007087/cac11a36-f3ba-11e6-89fe-57a3073f360c.png">

**Comment by Vernal** [comment]
Ok i'll test it again and report back.

**Comment by Vernal** [comment]
Ok you are right. Looked into it deeper and here are the findings:
https://replyable.com/2017/02/a-guide-to-wordpress-email-notifications-and-the-discussion-settings-screen/
