### ISSUE TITLE
Folks that did trial or had paid service, but switch back to free, are given the wrong message.

### ISSUE THREAD

**Issue by Vernal** [postmatic/postmatic-basic#97]
<img width="1283" alt="screen shot 2017-02-16 at 8 48 25 am" src="https://cloud.githubusercontent.com/assets/80932/23023700/c076211a-f424-11e6-878b-2334128d4504.png">

They should instead get the default upgrade message?

**Comment by cyberhobo** [comment]
Fixed by https://github.com/postmatic/postmatic-basic/commit/6d6b2ae175c0d07bd832b09953c031c466fed856.
